[package]
name = "rust-crypto-lib"
version = "0.1.0"
authors = ["Tobi Awolaju <tobi@example.com>"]
edition = "2021"

[dependencies]
rand = "0.8"
aes = "0.7"
rsa = "0.5"
sha2 = "0.9"

[dev-dependencies]
criterion = "0.3"
proptest = "1.0"
